main: com.thizthizzydizzy.movecraft.Movecraft
version: 1.1
api-version: 1.13
name: Movecraft
commands:
    movecraft:
        description: Reloads movecraft or toggles debug mode
        usage: /movecraft reload|debug [on|off]