main: com.thizthizzydizzy.aeronautics.Aeronautics
version: 0
api-version: 1.17
author: ThizThizzyDizzy
name: Aeronautics
commands:
    aeronautics:
        description: Aeronautics commands
        usage: /aeronautics (help|debug [on|off])